# - find RDKit
# RDKIT_INCLUDE_DIR - Where to find RDKit header files (directory)
# RDKIT_FINGERPRINT_LIBRARY - RDKit Fingerprint library
# RDKIT_SMILESPARSE_LIBRARY - RDKit SmilesParse library
# RDKIT_FOUND - Set to TRUE if we found everything (library, includes and executable)

# Copyright (c) 2010 Tim Vandermeersch
#
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.

IF( RDKIT_INCLUDE_DIR AND RDKIT_LIBRARIES )
    SET(RDKIT_FIND_QUIETLY TRUE)
ENDIF( RDKIT_INCLUDE_DIR AND RDKIT_LIBRARIES )

FIND_PATH( RDKIT_INCLUDE_DIR GraphMol/Atom.h PATHS ${RDKIT_ROOT}/Code )

FIND_LIBRARY(RDKIT_FINGERPRINTS_LIBRARY NAMES Fingerprints PATHS ${RDKIT_ROOT}/lib ${RDKIT_ROOT}/build/lib )
FIND_LIBRARY(RDKIT_SMILESPARSE_LIBRARY NAMES SmilesParse PATHS ${RDKIT_ROOT}/lib ${RDKIT_ROOT}/build/lib )

IF( RDKIT_FINGERPRINTS_LIBRARY AND RDKIT_SMILESPARSE_LIBRARY AND RDKIT_INCLUDE_DIR )
    SET( RDKIT_FOUND TRUE )
ENDIF( RDKIT_FINGERPRINTS_LIBRARY AND RDKIT_SMILESPARSE_LIBRARY AND RDKIT_INCLUDE_DIR )

IF( RDKIT_FOUND )
    IF( NOT RDKIT_FIND_QUIETLY )
        MESSAGE( STATUS "Found RDKit header file in ${RDKIT_INCLUDE_DIR}")
        MESSAGE( STATUS "Found RDKit libraries: ${RDKIT_FINGERPRINTS_LIBRARY} ${RDKIT_SMILESPARSE_LIBRARY}")
    ENDIF( NOT RDKIT_FIND_QUIETLY )
ELSE(RDKIT_FOUND)
    IF( RDKit_FIND_REQUIRED)
      MESSAGE( FATAL_ERROR "Could not find RDKit" )
    ELSE( RDKit_FIND_REQUIRED)
      MESSAGE( STATUS "Optional package RDKit was not found" )
    ENDIF( RDKit_FIND_REQUIRED)
ENDIF(RDKIT_FOUND)
